Repository bounswe/bounswe2019group1, pull requests merged in 2019-10, with the labels that each got.

#160 SignupPage is implemented
  practice-app/react-front-end/package-lock.json
  practice-app/react-front-end/src/index.js
  practice-app/react-front-end/src/views/SignupPage/SignupPage.js
Labels: Coding: Frontend

#164 Header, footer and background are modified
  practice-app/react-front-end/src/assets/img/dollar-hd.jpg
  practice-app/react-front-end/src/components/Footer/Footer.js
  practice-app/react-front-end/src/components/Header/HeaderLinks.js
  practice-app/react-front-end/src/views/LoginPage/LoginPage.js
  practice-app/react-front-end/src/views/SignupPage/SignupPage.js
Labels: Coding: Frontend, Effort: Low, Priority: Medium

#167 Update Login and Signup Page
  practice-app/react-front-end/src/views/LoginPage/LoginPage.js
  practice-app/react-front-end/src/views/SignupPage/SignupPage.js
Labels: Effort: Low, Priority: Medium

#190 Update the Login and Signup Pages
  practice-app/react-front-end/package-lock.json
  practice-app/react-front-end/package.json
  practice-app/react-front-end/src/components/CustomInput/CustomInput.js
  practice-app/react-front-end/src/environments/environment.private.js
  practice-app/react-front-end/src/environments/environment.prod.js
  practice-app/react-front-end/src/service/authentication.service.js
  practice-app/react-front-end/src/service/user.service.js
  practice-app/react-front-end/src/utils/auth-header.js
  practice-app/react-front-end/src/utils/responseHandlers.js
  practice-app/react-front-end/src/utils/validator.js
  practice-app/react-front-end/src/views/LoginPage/LoginPage.js
  practice-app/react-front-end/src/views/ProfilePage/ProfilePage.js
  practice-app/react-front-end/src/views/SignupPage/SignupPage.js
Labels: Coding: Frontend, Platform: Web, Status: Review Needed

#195 Profile page created, minor bugs fixed in interface
  practice-app/react-front-end/public/favicon.ico
  practice-app/react-front-end/src/assets/img/faces/ai.jpg
  practice-app/react-front-end/src/assets/img/favicon.png
  practice-app/react-front-end/src/assets/jss/material-kit-react/views/loginPage.js
  practice-app/react-front-end/src/assets/jss/material-kit-react/views/profilePage.js
  practice-app/react-front-end/src/components/Footer/Footer.js
  practice-app/react-front-end/src/components/Header/HeaderLinks.js
  practice-app/react-front-end/src/views/LoginPage/LoginPage.js
  practice-app/react-front-end/src/views/ProfilePage/ProfilePage.js
  practice-app/react-front-end/src/views/SignupPage/SignupPage.js
Labels: Coding: Frontend, Platform: Web, Priority: Medium

#201 Some icons modified.
  practice-app/react-front-end/src/views/SignupPage/SignupPage.js
Labels: Coding: Frontend, Effort: Low, Platform: Web, Priority: Low

#202 Implemented http request services for login and register.
  practice-app/react-front-end/src/service/authentication.service.js
  practice-app/react-front-end/src/service/getProfileInformation.js
  practice-app/react-front-end/src/service/registration.service.js
  practice-app/react-front-end/src/utils/auth-header.js
  practice-app/react-front-end/src/views/LoginPage/LoginPage.js
  practice-app/react-front-end/src/views/SignupPage/SignupPage.js
Labels: Coding: Frontend, Effort: Medium, Priority: High

#216 #215 Implemented password security requirement
  backend/tradersplatform/myuser/views.py
Labels: Priority: High

#220 Redirection to ProfilePage via token.
  practice-app/react-front-end/package-lock.json
  practice-app/react-front-end/package.json
  practice-app/react-front-end/src/views/LoginPage/LoginPage.js
  practice-app/react-front-end/src/views/ProfilePage/ProfilePage.js
Labels: Coding: Frontend, Effort: Low, Platform: Web, Priority: Medium

#237 Profile Page modified.
  practice-app/react-front-end/src/assets/img/examples/BTC17-1.jpg
  practice-app/react-front-end/src/assets/img/examples/po2.jpeg
  practice-app/react-front-end/src/assets/img/examples/ppp1.jpeg
  practice-app/react-front-end/src/assets/img/examples/ppp2.jpg
  practice-app/react-front-end/src/assets/img/examples/ppp3.jpg
  practice-app/react-front-end/src/assets/img/examples/ppp4.jpeg
  practice-app/react-front-end/src/assets/img/examples/pppp2.jpeg
  practice-app/react-front-end/src/components/ProfileHeader/Pheader.js
  practice-app/react-front-end/src/components/ProfileHeader/PheaderLinks.js
  practice-app/react-front-end/src/views/ProfilePage/ProfilePage.js
Labels: Coding: Frontend, Effort: Medium, Priority: High

#248 Validation message added.
  practice-app/react-front-end/package-lock.json
  practice-app/react-front-end/package.json
  practice-app/react-front-end/src/assets/img/examples/ev1.jpeg
  practice-app/react-front-end/src/assets/img/examples/ev2.jpeg
  practice-app/react-front-end/src/assets/img/examples/ev3.jpeg
  practice-app/react-front-end/src/assets/img/examples/ev4.jpg
  practice-app/react-front-end/src/assets/img/examples/ev5.jpeg
  practice-app/react-front-end/src/assets/img/examples/l1.jpeg
  practice-app/react-front-end/src/components/Header/HeaderLinks.js
  practice-app/react-front-end/src/components/ProfileHeader/PheaderLinks.js
  practice-app/react-front-end/src/service/registration.service.js
  practice-app/react-front-end/src/utils/validator.js
  practice-app/react-front-end/src/views/LoginPage/LoginPage.js
  practice-app/react-front-end/src/views/ProfilePage/ProfilePage.js
  practice-app/react-front-end/src/views/SignupPage/SignupPage.js
Labels: Coding: Frontend
